### ISSUE TITLE
Error when I run qgis_process

### ISSUE THREAD

**Issue by alxp7a** [NationalSecurityAgency/qgis-latlontools-plugin#79]
> C:\Users\USER\OneDrive - XXXXX\QGIS\Modeleur>"C:\Program Files\QGIS 3.28.4\bin\qgis_process-qgis-ltr.bat" run "C:\Users\USER\OneDrive - XXXXX\QGIS\Modeleur\save_XXXXX.model3"
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.4/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\latlontools\__init__.py", line 3, in classFactory
    return LatLonTools(iface)
  File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\latlontools\latLonTools.py", line 27, in __init__
    self.canvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'
error starting plugin: latlontools

**Comment by hamiltoncj** [comment]
If I am understanding this correctly, you are trying to use Lat Lon Tools outside of QGIS - perhaps to use one of the processing algorithms. If that is the case you are the first. Lat Lon Tools is geared to be run within the QGIS application environment and not outside it. I am guessing that is why iface is "NoneType". 

Theoretically, I could detect this and disable the code that is not related to the processing algorithms; however, I have a new supervisor who dislikes QGIS and is preventing me from working on these projects.

I will keep this ticket active until I see if I can get approval to fix it.

**Comment by florisvdh** [comment]
Having this fixed would allow to use Lat Lon Tools algorithms e.g. from R, using R package [qgisprocess](https://github.com/r-spatial/qgisprocess), which calls `qgis_process`. For example, that would be useful to handle MGRS coordinates in R (which has no native MGRS implementations AFAIK, also the PROJ library doesn't handle them). I'm no Python developer, but a few other plugins with similar problems got fixed for `qgis_process` (referenced in https://github.com/r-spatial/qgisprocess/issues/73), perhaps those cases may serve as inspiration but the problem seems different here.

FYI @JanCaha.

Indeed `qgis_process` currently struggles. Apparently it sees the plugin, and in the list of plugins `latlontools` is not marked as enabled even though it's enabled in the GUI (which it seems to report when trying to re-enable).

```bash
$ qgis_process plugins
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/__init__.py", line 3, in classFactory
    return LatLonTools(iface)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/latLonTools.py", line 27, in __init__
    self.canvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

error starting plugin: latlontools

Available plugins
(* indicates loaded plugins which implement Processing providers)

* QNEAT3
* processing_saga_nextgen
* pcraster_tools
* ViewshedAnalysis
  cartography_tools
* wbt_for_qgis
  latlontools
* grassprovider
* otbprovider
* processing

$ qgis_process plugins enable latlontools
Enabling plugin: "latlontools"
Plugin is already enabled!

$ qgis_process plugins
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/__init__.py", line 3, in classFactory
    return LatLonTools(iface)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/latLonTools.py", line 27, in __init__
    self.canvas = iface.mapCanvas()
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

error starting plugin: latlontools

Available plugins
(* indicates loaded plugins which implement Processing providers)

* QNEAT3
* processing_saga_nextgen
* pcraster_tools
* ViewshedAnalysis
  cartography_tools
* wbt_for_qgis
  latlontools
* grassprovider
* otbprovider
* processing

$ qgis_process --version
QGIS 3.30.2-'s-Hertogenbosch ''s-Hertogenbosch' (0992b53397)
QGIS code revision 0992b53397
Qt version 5.15.3
Python version 3.10.6
GDAL/OGR version 3.6.2
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.1
```

**Comment by florisvdh** [comment]
FYI `qgis_process` commands (or a JSON input string, also useful in R) can be copied from a QGIS processing (or history) dialog using the 'Advanced' button:

![afbeelding](https://user-images.githubusercontent.com/19164640/235917447-93b39146-ab72-4c78-a7be-a2a23d9e73c8.png)

**Comment by hamiltoncj** [comment]
@florisvdh @alxp7a 
Could you test this version of Lat Lon Tools to see if it works properly with qgis_process? You will need to go into Plugins->Manage and Install Plugins and then click on the Install from ZIP tab.

Thanks!

[latlontools_process_test.zip](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/files/11383174/latlontools_process_test.zip)

**Comment by hamiltoncj** [comment]
Excellent! I pushed out release 3.6.10 and is now in plugins.qgis.org. I also determined that two other of my plugins suffer the same issue so I will fix them as well.

**Comment by florisvdh** [comment]
Great idea, thanks!

**Comment by hamiltoncj** [comment]
I believe this to be solved so I am going close the ticket. I applied the same fix to 3 other plugins so thanks for reporting it, testing the new version, and providing detailed examples.
