### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by joaoponceleao** [NationalSecurityAgency/qgis-latlontools-plugin#9]
Getting the following issue in QGIS 2.18.7.
This is on mac, qgis installed via homebrew.
Looked at latlontools/settings.py file but don't see anything wrong there.
Last working version was perhaps 0.7/0.8.

```
Couldn't load plugin latlontools due to an error when calling its initGui() method 

TypeError: coercing to Unicode: need string or buffer, QPyNullVariant found 
Traceback (most recent call last):
  File "/usr/local/Cellar/qgis2/2.18.7_1/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/Users/joao/.qgis2/python/plugins/latlontools/latLonTools.py", line 30, in initGui
    self.settingsDialog = SettingsWidget(self, self.iface, self.iface.mainWindow())
  File "/Users/joao/.qgis2/python/plugins/latlontools/settings.py", line 59, in __init__
    self.readSettings()
  File "/Users/joao/.qgis2/python/plugins/latlontools/settings.py", line 129, in readSettings
    if not os.path.isfile(self.qmlStyle):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, QPyNullVariant found
```

**Comment by hamiltoncj** [comment]
I have no idea why you should be getting that error. The issue I face is that I don't have a Mac to test against, but I have put in some checks for NULL cases. What I don't know is how you could have been getting a QPyNullVariant value.

I release version 0.9.2 which I hope will fix this problem.

Let me know if this has fixed the issue.

Thanks for bring this to my attention!!!

**Comment by joaoponceleao** [comment]
Thanks for the quick response!!!
Its fixed now so I'm closing the issue.
This comes with a caveat for anyone else having this issue though. An upgrade will not take care of the issue. It requires an uninstall and reinstall of the plugin.
Same reinstall tactic did not work before though, so the NULL checks must have helped.
